#!/usr/bin/env python3
"""Save citation output generated by the blueprint-citation skill."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path


def save_citation_output(data: dict, output_dir: Path = Path(".")) -> Path:
    """Save citation data to a timestamped JSON + Markdown file."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    base = output_dir / f"citation_{timestamp}"

    # Save raw JSON
    json_path = base.with_suffix(".json")
    json_path.write_text(json.dumps(data, indent=2), encoding="utf-8")

    # Save a simple Markdown summary if 'markdown' key exists
    if "markdown" in data:
        md_path = base.with_suffix(".md")
        md_path.write_text(data["markdown"], encoding="utf-8")

    return json_path


if __name__ == "__main__":
    import sys

    if len(sys.argv) < 2:
        print("Usage: python save_citation.py <json_file_or_-for-stdin>")
        sys.exit(1)

    if sys.argv[1] == "-":
        data = json.load(sys.stdin)
    else:
        data = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))

    out_path = save_citation_output(data)
    print(f"Saved to {out_path}")
